### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by jgmize** [mozmeao/cloudflare-datadog#4]
See https://github.com/mozmar/cloudflare-datadog/pull/3#issue-213566077

**Comment by so0k** [comment]
I just pushed [our internal helm chart for cloudflare-datadog](https://github.com/honestbee/public-charts/tree/cloudflare-datadog-0.1.0/incubator/cloudflare-datadog) to our public-charts - note that this helm chart refers to honestbee [cloudflare-datadog repo on quay.io](https://quay.io/repository/honestbee/cloudflare-datadog)

I suggest you create an official cloudflare-datadog repo (perhaps on hub.docker.com) and create auto builds.

Then I can re-work my helm chart to refer to that image and we can do a PR to [the official Kubernetes Helm charts repo](https://github.com/kubernetes/charts).

I also have [a re-worked healthchecks.io image](https://github.com/honestbee/healthchecks), which I'll create another helm chart for as well.

**Comment by so0k** [comment]
[Install Helm on client and in cluster](https://github.com/kubernetes/helm#install)

Use the sample honestbee helm repo server:

Provide secrets config (i.e. `.secrets.yaml`):
```yaml
config:
  stats-key-prefix: "cloudflare"
  since: "-360"
  tags: "cloudflare,honestbee"
secrets:
  datadog-api-key: "<datadog-api-key>"
  datadog-app-key: "<datadog-app-key"
  auth-email: "<cf-email>"
  auth-key: "<cf-key>"
  zone: "<cf-zone-id>"
  dead-mans_snitch-url: "https://hchk.io/<check-id>"
```

```bash
$ helm repo add honestbee-charts http://tech.honestbee.com/public-charts
"honestbee-charts" has been added to your repositories
$ helm repo list
NAME                    URL
kubernetes-charts       http://storage.googleapis.com/kubernetes-charts
honestbee-charts        http://tech.honestbee.com/public-charts
$ helm search cloudflare
NAME                                    VERSION DESCRIPTION
honestbee-charts/cloudflare-datadog     0.1.0   A Helm chart for cloudflare-datadog service
$ helm install -n cfdd --debug --dry-run -f .secrets.yaml honestbee-charts/cloudflare-datadog
```

Or, Instructions for you to try out the Helm chart in the PR  to the official repo (if it ever gets merged).

Clone honestbee/public-charts repo & use `cloudflare-datadog-0.1.0` branch
```bash
git clone git@github.com:honestbee/public-charts.git
git checkout cloudflare-datadog-0.1.0
cd incubator/cloudflare-datadog/
```

Dry run from local dir:
```bash
helm install -n cfdd --debug --dry-run -f .secrets.yaml .
```

If happy with the result, actually install the chart to the cluster:
```
helm install -n cfdd -f .secrets.yaml .
```
